In [1]:
import numpy as np 
import pandas as pd

In [2]:
movies = pd.read_csv("dataset/tmdb_5000_movies.csv")
credits = pd.read_csv("dataset/tmdb_5000_credits.csv")

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
movies = movies.merge(credits,on = 'title')

In [5]:
movies.shape

(4809, 23)

In [6]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies =movies[['movie_id','genres','keywords','title','overview','cast','crew']]

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   genres    4809 non-null   object
 2   keywords  4809 non-null   object
 3   title     4809 non-null   object
 4   overview  4806 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [8]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)
print("that's are duplicate",movies.duplicated().sum())

that's are duplicate 0

In [10]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [12]:
movies['genres'] = movies['genres'].apply(convert)

In [13]:
movies.head(1)

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head(1)

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [15]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
        else:
            break
    return L

In [16]:
movies['cast'] = movies['cast'].apply(convert3)
movies['crew'].head(1)

0    [{"credit_id": "52fe48009251416c750aca23", "de...
Name: crew, dtype: object

In [17]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] =='Director':
            L.append(i['name'])
            break
    return L

In [18]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [19]:
movies['crew'].head(10)

0        [James Cameron]
1       [Gore Verbinski]
2           [Sam Mendes]
3    [Christopher Nolan]
4       [Andrew Stanton]
5            [Sam Raimi]
6         [Byron Howard]
7          [Joss Whedon]
8          [David Yates]
9          [Zack Snyder]
Name: crew, dtype: object

In [20]:
movies.head(10)

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]
5,559,"[Fantasy, Action, Adventure]","[dual identity, amnesia, sandstorm, love of on...",Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,"[Tobey Maguire, Kirsten Dunst, James Franco, T...",[Sam Raimi]
6,38757,"[Animation, Family]","[hostage, magic, horse, fairy tale, musical, p...",Tangled,When the kingdom's most wanted-and most charmi...,"[Zachary Levi, Mandy Moore, Donna Murphy, Ron ...",[Byron Howard]
7,99861,"[Action, Adventure, Science Fiction]","[marvel comic, sequel, superhero, based on com...",Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,"[Robert Downey Jr., Chris Hemsworth, Mark Ruff...",[Joss Whedon]
8,767,"[Adventure, Fantasy, Family]","[witch, magic, broom, school of witchcraft, wi...",Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...","[Daniel Radcliffe, Rupert Grint, Emma Watson, ...",[David Yates]
9,209112,"[Action, Adventure, Fantasy]","[dc comics, vigilante, superhero, based on com...",Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,"[Ben Affleck, Henry Cavill, Gal Gadot, Amy Ada...",[Zack Snyder]

In [21]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [22]:
movies['overview']= movies['overview'].apply(lambda x:x.split())

In [23]:
movies.head(1)

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]

In [24]:
movies['genres'] = movies['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['keywords'] = movies['keywords'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['cast'] = movies['cast'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['crew'] = movies['crew'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)

In [25]:
movies.head(1)

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]

In [26]:
movies['tags'] = movies['genres'] + movies['overview'] + movies['keywords'] + movies['cast'] + movies['crew']

In [27]:
movies.head(1)

,movie_id,genres,keywords,title,overview,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, I..."

In [28]:
new_df = movies[['movie_id', 'title', 'tags']]

In [29]:
print(new_df.head())
print(type(new_df))

   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                tags
0  [Action, Adventure, Fantasy, ScienceFiction, I...
1  [Adventure, Fantasy, Action, Captain, Barbossa...
2  [Action, Adventure, Crime, A, cryptic, message...
3  [Action, Crime, Drama, Thriller, Following, th...
4  [Action, Adventure, ScienceFiction, John, Cart...
<class 'pandas.core.frame.DataFrame'>

In [30]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Coders\AppData\Local\Temp\ipykernel_12220\1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [31]:
print(new_df['tags'].head())

0    Action Adventure Fantasy ScienceFiction In the...
1    Adventure Fantasy Action Captain Barbossa, lon...
2    Action Adventure Crime A cryptic message from ...
3    Action Crime Drama Thriller Following the deat...
4    Action Adventure ScienceFiction John Carter is...
Name: tags, dtype: object

In [32]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [33]:
def stem(text):
    y  = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [34]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Coders\AppData\Local\Temp\ipykernel_12220\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [35]:
new_df

,movie_id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict in the 22n...
1,285,Pirates of the Caribbean: At World's End,"adventur fantasi action captain barbossa, long..."
2,206647,Spectre,action adventur crime a cryptic messag from bo...
3,49026,The Dark Knight Rises,action crime drama thriller follow the death o...
4,49529,John Carter,action adventur sciencefict john carter is a w...
...,...,...,...
4804,9367,El Mariachi,action crime thriller el mariachi just want to...
4805,72766,Newlyweds,comedi romanc a newlyw couple' honeymoon is up...
4806,231617,"Signed, Sealed, Delivered","comedi drama romanc tvmovi ""signed, sealed, de..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,documentari ever sinc the second grade when he...

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
vectors = cv.fit_transform(new_df['tags']).toarray()

In [37]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(81492,))

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity =cosine_similarity(vectors)

In [40]:
similarity

array([[1.        , 0.11960262, 0.08873772, ..., 0.14250133, 0.09458888,
        0.07498438],
       [0.11960262, 1.        , 0.16001536, ..., 0.19208062, 0.21165742,
        0.12695167],
       [0.08873772, 0.16001536, 1.        , ..., 0.17873565, 0.12942582,
        0.11704115],
       ...,
       [0.14250133, 0.19208062, 0.17873565, ..., 1.        , 0.28820643,
        0.17452778],
       [0.09458888, 0.21165742, 0.12942582, ..., 0.28820643, 1.        ,
        0.2316945 ],
       [0.07498438, 0.12695167, 0.11704115, ..., 0.17452778, 0.2316945 ,
        1.        ]], shape=(4806, 4806))

In [41]:
new_df[new_df['title'] == 'The Lego Movie'].index[0]

np.int64(744)

In [42]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x: x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [43]:
recommend('Batman Begins')

The Midnight Meat Train
Gladiator
The Dark Knight
The Work and the Glory II: American Zion
Roadside Romeo

In [44]:
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

In [45]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [46]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [47]:
pickle.dump(similarity,open('similarity.pkl','wb'))